openapi: 3.0.1
info:
  title: FinancialGatewayBackend
  description: API Definition of FinancialGatewayBackend
  version: 1.0.0
servers:
- url: /FinancialGatewayBackend
paths:
  /FinancialGateway/{financialgatewayid}/Outbound/{outboundid}/Initiate:
    post:
      parameters:
      - name: financialgatewayid
        in: path
        required: true
        schema:
          type: string
      - name: outboundid
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
