openapi: 3.0.1
info:
  title: RegulatoryCompliance
  description: This service domain provides a service to interpret regulatory requirements,
    provide guidance and define and implement a portfolio of regulatory compliance
    tests across all appropriate bank activities
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
- url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/RegulatoryCompliance/11.0.0
paths:
  /RegulatoryCompliance/Evaluate:
    post:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: EvCR Start a compliance evaluation assessment
      description: EvCR Start a compliance evaluation assessment
      operationId: Evaluate
      requestBody:
        $ref: '#/components/requestBodies/EvaluateRegulatoryComplianceAssessmentRequest'
      responses:
        '200':
          description: EvaluateRegulatoryComplianceAssessmentResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentResponse'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '429':
          description: TooManyRequests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  /RegulatoryCompliance/{regulatorycomplianceid}/Update:
    put:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: UpCR Update submitted details or content for an on-going compliance
        assessment
      description: UpCR Update submitted details or content for an on-going compliance
        assessment
      operationId: Update
      parameters:
      - name: regulatorycomplianceid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/UpdateRegulatoryComplianceAssessmentRequest'
      responses:
        '200':
          description: UpdateRegulatoryComplianceAssessmentResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateRegulatoryComplianceAssessmentResponse'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '429':
          description: TooManyRequests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  /RegulatoryCompliance/{regulatorycomplianceid}/Request:
    put:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: RqCR Request a review or adjudication for an assessment
      description: RqCR Request a review or adjudication for an assessment
      operationId: Request
      parameters:
      - name: regulatorycomplianceid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/RequestRegulatoryComplianceAssessmentRequest'
      responses:
        '200':
          description: RequestRegulatoryComplianceAssessmentResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestRegulatoryComplianceAssessmentResponse'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '429':
          description: TooManyRequests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  /RegulatoryCompliance/{regulatorycomplianceid}/Retrieve:
    get:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: ReCR Retrieve details and content from an active compliance assessment
      description: ReCR Retrieve details and content from an active compliance assessment
      operationId: Retrieve
      parameters:
      - name: regulatorycomplianceid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: RetrieveRegulatoryComplianceAssessmentResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveRegulatoryComplianceAssessmentResponse'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '429':
          description: TooManyRequests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    RegulatoryComplianceAssessment:
      type: object
      properties:
        RegulatoryAssessmentType:
          type: string
          description: The type and make-up of regulatory tests referenced in the
            assessment
          format: string
        BusinessUnitReference:
          type: string
          description: The business function or unit assessed for compliance if appropriate
          format: object
        ProductandServiceReference:
          type: string
          description: The associated product/service being assessed if appropriate
          format: object
        CustomerReference:
          type: string
          description: Reference to the customer assessed if appropriate
          format: object
        RegulatoryAuthorityReference:
          type: string
          description: Indication of the authority pertaining to the applied regulation
          format: object
        RegulationReference:
          type: string
          description: Reference to the specific regulation
          format: object
        RegulationDefinition:
          type: string
          description: A definition of the goals/required actions addressed by the
            regulation
          format: string
        RegulationComplianceandReportingRequirements:
          type: string
          description: Description of the measurements and reporting required to demonstrate
            compliance
          format: string
        RegulationAccountability:
          type: string
          description: Explanation of the business context, responsibility and accountability
            for compliance
          format: string
        RegulationPenalties:
          type: string
          description: Outline of the possible implications of non-compliance
          format: string
        RegulationGuideline:
          type: string
          description: Guidelines and requirements for compliance
          format: string
        DocumentReference:
          type: string
          description: Reference to any documentation classified/archived as appropriate
          format: object
        RegulatoryAssessmentWorkProducts:
          type: string
          description: Work documentation, forms and schedules produced and referenced
            during the assessment
          format: string
        RegulatoryAssessmentResult:
          type: string
          description: Outcome/result of the assessment, can include remedial actions
          format: string
      description: 'To test or assess an entity, possibly against some formal qualification
        or certification requirement within Regulatory Compliance. '
    EvaluateRegulatoryComplianceAssessmentRequest:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentRequest_RegulatoryComplianceAssessment'
      description: 'Input: EvCR Start a compliance evaluation assessment'
    EvaluateRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentResponse_RegulatoryComplianceAssessment'
      description: 'Output: EvCR Start a compliance evaluation assessment'
    UpdateRegulatoryComplianceAssessmentRequest:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentRequest_RegulatoryComplianceAssessment'
      description: 'Input: UpCR Update submitted details or content for an on-going
        compliance assessment'
    UpdateRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentRequest_RegulatoryComplianceAssessment'
      description: 'Output: UpCR Update submitted details or content for an on-going
        compliance assessment'
    RequestRegulatoryComplianceAssessmentRequest:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentRequest_RegulatoryComplianceAssessment'
      description: 'Input: RqCR Request a review or adjudication for an assessment'
    RequestRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/RequestRegulatoryComplianceAssessmentResponse_RegulatoryComplianceAssessment'
      description: 'Output: RqCR Request a review or adjudication for an assessment'
    RetrieveRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          $ref: '#/components/schemas/RetrieveRegulatoryComplianceAssessmentResponse_RegulatoryComplianceAssessment'
      description: 'Output: ReCR Retrieve details and content from an active compliance
        assessment'
    EvaluateRegulatoryComplianceAssessmentRequest_RegulatoryComplianceAssessment:
      type: object
      properties:
        RegulatoryAssessmentType:
          type: string
          format: string
        BusinessUnitReference:
          type: string
          format: object
        ProductandServiceReference:
          type: string
          format: object
        CustomerReference:
          type: string
          format: object
        RegulatoryAuthorityReference:
          type: string
          format: object
        RegulationReference:
          type: string
          format: object
        DocumentReference:
          type: string
          format: object
        RegulatoryAssessmentWorkProducts:
          type: string
          format: string
    EvaluateRegulatoryComplianceAssessmentResponse_RegulatoryComplianceAssessment:
      type: object
      properties:
        RegulatoryAssessmentType:
          type: string
          format: string
        RegulationDefinition:
          type: string
          format: string
        RegulationComplianceandReportingRequirements:
          type: string
          format: string
        RegulationAccountability:
          type: string
          format: string
        RegulationPenalties:
          type: string
          format: string
        RegulationGuideline:
          type: string
          format: string
        DocumentReference:
          type: string
          format: object
        RegulatoryAssessmentWorkProducts:
          type: string
          format: string
        RegulatoryAssessmentResult:
          type: string
          format: string
    RequestRegulatoryComplianceAssessmentResponse_RegulatoryComplianceAssessment:
      type: object
      properties:
        RegulatoryAssessmentType:
          type: string
          format: string
        BusinessUnitReference:
          type: string
          format: object
        ProductandServiceReference:
          type: string
          format: object
        CustomerReference:
          type: string
          format: object
        RegulatoryAuthorityReference:
          type: string
          format: object
        RegulationReference:
          type: string
          format: object
        DocumentReference:
          type: string
          format: object
        RegulatoryAssessmentWorkProducts:
          type: string
          format: string
        RegulatoryAssessmentResult:
          type: string
          format: string
    RetrieveRegulatoryComplianceAssessmentResponse_RegulatoryComplianceAssessment:
      type: object
      properties:
        RegulatoryAssessmentType:
          type: string
          format: string
        BusinessUnitReference:
          type: string
          format: object
        ProductandServiceReference:
          type: string
          format: object
        CustomerReference:
          type: string
          format: object
        RegulatoryAuthorityReference:
          type: string
          format: object
        RegulationReference:
          type: string
          format: object
        RegulationDefinition:
          type: string
          format: string
        RegulationComplianceandReportingRequirements:
          type: string
          format: string
        RegulationAccountability:
          type: string
          format: string
        RegulationPenalties:
          type: string
          format: string
        RegulationGuideline:
          type: string
          format: string
        DocumentReference:
          type: string
          format: object
        RegulatoryAssessmentWorkProducts:
          type: string
          format: string
        RegulatoryAssessmentResult:
          type: string
          format: string
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    EvaluateRegulatoryComplianceAssessmentResponse:
      description: EvaluateRegulatoryComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentResponse'
    UpdateRegulatoryComplianceAssessmentResponse:
      description: UpdateRegulatoryComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateRegulatoryComplianceAssessmentResponse'
    RequestRegulatoryComplianceAssessmentResponse:
      description: RequestRegulatoryComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestRegulatoryComplianceAssessmentResponse'
    RetrieveRegulatoryComplianceAssessmentResponse:
      description: RetrieveRegulatoryComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveRegulatoryComplianceAssessmentResponse'
  parameters:
    regulatorycomplianceid:
      name: regulatorycomplianceid
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateRegulatoryComplianceAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentRequest'
      required: true
    UpdateRegulatoryComplianceAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateRegulatoryComplianceAssessmentRequest'
      required: true
    RequestRegulatoryComplianceAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestRegulatoryComplianceAssessmentRequest'
      required: true
