openapi: 3.0.1
info:
  title: RegulatoryComplianceBackend
  description: API Definition of RegulatoryComplianceBackend
  version: 1.0.0
servers:
- url: http://localhost:8290/RegulatoryCompliance
paths:
  /RegulatoryCompliance/Evaluate:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
